name: Update TFVars

on:
  push:
    branches:
      - main

jobs:
  update-tfvars:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"

      - name: Create Branch
        run: |
          git checkout -b update-tfvars-${{ github.run_number }}

      - name: Update TFVars
        run: |
          cd Route53
          sed -i 's/ALB_URL=.*/ALB_URL=new_url/' testing.tfvar

      - name: Commit and Push Changes
        run: |
          git add path/to/your/file1.tfvar
          git commit -m "Update ALB_URL to new_url"
          git push origin update-tfvars-${{ github.run_number }}
