name: Automate Git Actions

on:
  workflow_dispatch:
    inputs:
      repository_name:
        description: 'Repository Name'
        required: true
      new_branch_name:
        description: 'New Branch Name'
        required: true
      commit_message:
        description: 'Commit Message'
        required: true
      user_email:
        description: 'User Email'
        required: true
      user_name:
        description: 'User Name'
        required: true

jobs:
  automate:
    runs-on: ubuntu-latest

    env:
      REPOSITORY_NAME: ${{ github.event.inputs.repository_name }}
      NEW_BRANCH_NAME: ${{ github.event.inputs.new_branch_name }}
      COMMIT_MESSAGE: ${{ github.event.inputs.commit_message }}
      USER_EMAIL: ${{ github.event.inputs.user_email }}
      USER_NAME: ${{ github.event.inputs.user_name }}
      
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Configure Git
      run: |
        git config user.email "${{ env.USER_EMAIL }}"
        git config user.name "${{ env.USER_NAME }}"
        git config push.default current

    - name: Create and switch to a new branch
      run: git checkout -b ${{ env.NEW_BRANCH_NAME }}

    - name: Make changes for testing
      run: echo "Testing changes" >> test.txt  # Add your testing changes here

    # Do the required changes

    - name: Commit changes
      run: |
        git add .
        git commit -m "${{ env.COMMIT_MESSAGE }}"

    - name: Check if there are no uncommitted changes
      run: |
        if [[ -z $(git status --porcelain) ]]; then
          echo "No changes to commit. Proceeding to push."
        else
          echo "Error: There are uncommitted changes. Please commit or discard them."
          exit 1
        fi

    - name: Push changes
      run: git push origin ${{ env.NEW_BRANCH_NAME }}
