name: Update TFVars

on:
  push:
    branches:
      - main

jobs:
  update-tfvars:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@gmail.com"

      - name: Create Branch
        run: git checkout -b update-tfvars-${{ github.run_number }}

      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}

      - name: Update TFVars
        run: sed -i 's/ALB_URL=.*/ALB_URL=second_url/' /home/runner/work/Route53/Route53/testing.tfvars
        
      - name: Debug PAT
        run: |
         echo "PAT_TOKEN: $PAT_TOKEN"
         
      - name: Commit and Push Changes
        run: |
          git add /home/runner/work/Route53/Route53/testing.tfvars
          git commit -m "Update ALB_URL to new_url"
          git push origin update-tfvars-${{ github.run_number }}
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
